services:
  db:
    container_name: postgres
    image: postgres:15.4
    environment:
      POSTGRES_USER: kursph
      POSTGRES_PASSWORD: password
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - postgres
    restart: unless-stopped
  kursph-api:
    container_name: kursph-api
    image: kurshjku/kursph-spring-boot-api
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/customer
    ports:
      - "8080:8080"
    networks:
      - postgres
    depends_on:
      - db
    restart: unless-stopped
  kursph-react:
    container_name: kursph-react
    image: kurshjku/kursph-react
    build:
      context: frontend/react
      dockerfile: Dockerfile
    ports:
      - "3000:5173"
    depends_on:
      - kursph-api
    restart: unless-stopped
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - "5050:80"
    networks:
      - postgres
    restart: unless-stopped
    depends_on:
      - db

networks:
  postgres:
    driver: bridge

volumes:
  postgres:
  pgadmin: