aws:
  s3:
    mock: false

spring:
  datasource:
    url: jdbc-secretsmanager:postgresql://awseb-e-qgx3j4yfdq-stack-awsebrdsdatabase-zutwbiex3ibo.cwfngv7mxbca.eu-central-1.rds.amazonaws.com:5432/ebdb
    username: test/kursph-api/postgres
    driver-class-name: com.amazonaws.secretsmanager.sql.AWSSecretsManagerPostgreSQLDriver
