aws:
  s3:
    mock: false

spring:
  datasource:
    url: jdbc:postgresql://awseb-e-f3tym6qff2-stack-awsebrdsdatabase-wvtoebgglkgf.cwfngv7mxbca.eu-central-1.rds.amazonaws.com:5432/ebdb
    username: kursph
    password: password
