server:
  port: 8080
  error:
    include-message: always

cors:
  allowed-origins: "*"
  allowed-methods: "*"
  allowed-headers: "*"
  exposed-headers: "*"

aws:
  region: eu-central-1
  s3:
    bucket-name: elasticbeanstalk-eu-central-1-624739824262

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/customer
    username: kursph
    password: password
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true
  main:
    web-application-type: servlet

management:
  endpoints:
    web:
      exposure:
        include: "health,info"